import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, useForm } from '@inertiajs/react';

export default function Index({ auth, codes, documents }) {
    const { data, setData, post, processing, errors, reset } = useForm({
        document_id: '',
        count: 1,
    });

    const submit = (e) => {
        e.preventDefault();
        post(route('codes.generate'), {
            onSuccess: () => reset(),
        });
    };

    return (
        <AuthenticatedLayout
            user={auth.user}
            header={<h2 className="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">Cash Payment Codes</h2>}
        >
            <Head title="Payment Codes" />

            <div className="py-12">
                <div className="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
                    <div className="p-4 sm:p-8 bg-white dark:bg-gray-800 shadow sm:rounded-lg">
                        <header>
                            <h2 className="text-lg font-medium text-gray-900 dark:text-gray-100">Generate Codes</h2>
                            <p className="mt-1 text-sm text-gray-600 dark:text-gray-400">
                                Generate codes for people who pay cash.
                            </p>
                        </header>

                        <form onSubmit={submit} className="mt-6 space-y-6 max-w-xl">
                            <div>
                                <label className="block font-medium text-sm text-gray-700 dark:text-gray-300">Newspaper (Optional)</label>
                                <select
                                    className="mt-1 block w-full border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"
                                    value={data.document_id}
                                    onChange={(e) => setData('document_id', e.target.value)}
                                >
                                    <option value="">Any Newspaper ($1 credit)</option>
                                    {documents.map((doc) => (
                                        <option key={doc.id} value={doc.id}>{doc.title}</option>
                                    ))}
                                </select>
                            </div>

                            <div>
                                <label className="block font-medium text-sm text-gray-700 dark:text-gray-300">Number of Codes</label>
                                <input
                                    type="number"
                                    min="1"
                                    max="100"
                                    className="mt-1 block w-full border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"
                                    value={data.count}
                                    onChange={(e) => setData('count', e.target.value)}
                                    required
                                />
                            </div>

                            <div className="flex items-center gap-4">
                                <button
                                    type="submit"
                                    className="px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 disabled:opacity-50"
                                    disabled={processing}
                                >
                                    Generate
                                </button>
                            </div>
                        </form>
                    </div>

                    <div className="p-4 sm:p-8 bg-white dark:bg-gray-800 shadow sm:rounded-lg">
                        <header>
                            <h2 className="text-lg font-medium text-gray-900 dark:text-gray-100">Recent Codes</h2>
                        </header>

                        <div className="mt-6">
                            <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                                <thead>
                                    <tr>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Code</th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Document</th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Generated By</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                                    {codes.data.map((code) => (
                                        <tr key={code.id}>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm font-mono font-bold text-gray-900 dark:text-gray-100">{code.code}</td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-gray-100">{code.document ? code.document.title : 'Any'}</td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm">
                                                {code.is_used ? (
                                                    <span className="text-red-500">Used by {code.user?.name}</span>
                                                ) : (
                                                    <span className="text-green-500 font-bold">Available</span>
                                                )}
                                            </td>
                                            <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-gray-100">{code.generator.name}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}
